[package]
name = "iotics-grpc-client"
version = "0.1.0"
authors = ["Mihai Dinculescu <mihai.dinculescu@iotic-labs.com>"]
edition = "2018"

[dependencies]
tonic = "0.5"
prost = "0.8"
prost-types = "0.8"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "time"] }
dotenv = "0.15.0"
rand = "0.8"
anyhow = "1.0"

iotics-identity = { git = "ssh://git@github.com/Iotic-Labs/iotics-identity-rust.git" }

[build-dependencies]
tonic-build = "0.5"
