[package]
name = "iotics-grpc-client"
version = "0.1.0"
authors = ["Mihai Dinculescu <mihai.dinculescu@iotic-labs.com>"]
edition = "2021"

[dependencies]
tonic = { version = "0.6", features = ["tls-webpki-roots"] }
prost = "0.9"
prost-types = "0.9"
tokio = { version = "1.15", features = ["macros", "rt-multi-thread", "time"] }
rand = "0.8"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tonic-build = "0.6"
